language: php

php:
  - 5.6
  - 7.0

before_script:
  - travis_retry composer self-update
  - travis_retry composer update --prefer-source $PREFER_LOWEST

script:
  - php vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover